### PR TITLE
Fix option lookup for auto deleting branches feature

### LINKED ISSUE #9: The auto-delete option is not working
We've been using this tool with auto deleting branches but we noticed that feature isn't working. Reviewing the changes, the option is exposed in doc/examples as `auto-delete` but the code is looking for an `auto-input` option instead.

https://github.com/plm9606/automerge_actions/blob/4596cf36c9a61ae24ed8da0ff7e54a18e5348295/src/index.js#L11

### PR DESCRIPTION
**Pull request by javierjulio**
This resolves issue #9 by looking up the option `auto-delete` instead of `auto-input` for supporting auto deleting of branches.

Fixes #9

### CODE REVIEW

**Comment by plm9606** [comment]
Thanks for fixing it!

**Comment by javierjulio** [comment]
@plm9606 thank you for your work on this! ❤️

Will you be able to release a new version of the action with this fix?

**Comment by plm9606** [comment]
@javierjulio I just released it!

**Comment by javierjulio** [comment]
@plm9606 thanks so much! We'll update now. ❤️

**Pull request merged**
